### ISSUE TITLE
Dasted fails to compile with DMD v2.067

### ISSUE THREAD

**Issue by stonemaster** [Groterik/dasted#1]
If trying to execute `dub build --build=release` I get the following error:

```
thirdparty/DCD/containers/src/std/allocator.d(4364): Warning: instead of C-style syntax, use D-style syntax 'Allocator[(max - (min - 1)) / step] buckets'
FAIL .dub/build/application-release-linux.posix-x86_64-dmd_2067-9F6DAF8946D2C8BF74965578D69A3E9E/ dasted executable
Error executing command build:
dmd failed with exit code 1.
```

Using `-v` gets the DMD command line used. The problem is that the warning `Warning: instead of C-style syntax, use D-style syntax 'Allocator[(max - (min - 1)) / step] buckets'` triggers a `1` exit code for DMD which leads DUB to think that the compilation failed. The root cause is that the used library isn't prepared for v2.067 yet (maybe switchting to a more recent submodule revision helps?)

On a side note: It would be great to have just a little README on how to compile Dasted. The command `git submodule update --init --recursive` is required before compiling the first time and that isn't immediately obvious imho.

Thanks.
